### ISSUE TITLE
ajax 请求后的 log 有可能是空的

### ISSUE THREAD

**Issue by Dianliang233** [Teahouse-Studios/mcwzh-meme-web-builder-server-ts#5]
![17}VPNO{{8X$H(JAS9`O8ST](https://user-images.githubusercontent.com/45287180/137585117-f2ffeeb5-0b26-449e-9b00-fee8691a1dad.png)

**Comment by XxLittleCxX** [comment]
现在根本没logs了

**Comment by Dianliang233** [comment]
是真的吗

**Comment by XxLittleCxX** [comment]
![image](https://gchat.qpic.cn/gchatpic_new/1445957253/657876815-3215546805-D67D4654AE00E770BFB42A3243A3EF5C/0?term=3)
